# Generated by Django 4.2.3 on 2023-07-19 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0002_rename_owner_snack_purchaser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='snack',
            old_name='purchaser',
            new_name='owner',
        ),
        migrations.AlterField(
            model_name='snack',
            name='description',
            field=models.TextField(default='generic description'),
        ),
    ]
